[project]
name = "modal-mcp-server"
version = "0.1.0"
description = "Utilities for interacting with Modal via LLM tool use"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datadog-api-client>=2.34.0",
    "mcp[cli]>=1.8.0",
    "modal>=0.76.4",
]
